---
# tasks file for redhat
- name : 'install apache server on ubuntu'
  apt:
    name: apache2
    state: latest
- name: 'copy index file'
  template:
    src: index.html.j2
    dest: "{{doc_root}}/index.html"
    owner: root
    group: root
    mode: 0755
  vars:
    os: "{{ansible_os_family}}"
    host: "{{ansible_hostname}}"
    env: prod
  notify:
  - Restart apache2 
- name: 'start service'
  service:
    name: apache2
    state: started
